# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
  react-native:
    name: Android Detox
    environment:
      node: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm Install
      - name: Install detox dependencies
        script: |
          brew tap wix/brew
      - name: Install detox-cli
        script: |
          npm install -g detox-cli
          cd $FCI_BUILD_DIR && npm install detox --save-dev
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Generate debug keystore
        script: |
          rm -f ~/.android/debug.keystore
          keytool -genkeypair \
            -alias androiddebugkey \
            -keypass android \
            -keystore $FCI_BUILD_DIR/android/app/debug.keystore \
            -storepass android \
            -dname 'CN=Android Debug,O=Android,C=US' \
            -keyalg 'RSA' \
            -keysize 2048 \
            -validity 10000
      - name: Build with Detox
        script: |
          detox build -c android.emu.debug
      - name: Test with Detox
        script: |
          detox test -c android.emu.debug
      - name: Build Android debug
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
