# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
  react-native:
    name: Android Detox
    environment:
      node: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm Install
      - name: Install detox dependencies
        script: |
          brew tap wix/brew
      - name: Install detox-cli
        script: |
          npm install -g detox-cli
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      - |
        # build Android
        cd android
        ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
